# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: utf-8
lang: pt-BR
title: Lumi
author: bsides
# email: rafaelbsides@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Progresso do jogo de RPG Lumi feito no RPG Maker MV.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lumirpg.tk" # the base hostname & protocol for your site, e.g. http://example.com

# Meta
excerpt_separator: <!--more-->
repository:        lumirpg/blog
timezone:          America/Sao_Paulo
google_analytics:  UA-50702825-2
sass:
  style: compressed

# Pagination
paginate: 6
paginate_path: /pag:num/

# Social
disqus:
  shortname: lumirpg
twitter:
  username:  bsides
github:
  username:  bsides
discord:
  username:  bsides#9436
forum:
  username:  bsides

# More seo
google_site_verification: ZGsNrIols3GdSvN2pcpKdpBVeTwYMFMptRq08ZRBpJU

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
